language: node_js

sudo: false

node_js:
  - 4
  - 5
  - 6

install:
  - npm install -g yarn
  - yarn install

script:
  - npm run test

after_success:
  - cat ./test/unit/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

notifications:
  email:
    on_success: never
    on_failure: change
